# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'A_Simple_List' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for A_Simple_List
  pod 'MCSwipeTableViewCell', '~> 2.1.4'
  pod 'Charts'
  pod 'RealmSwift', '~> 2.0.2'
end
